### ISSUE TITLE
Verify Additional Endpoints

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-prism-source#4]
[PRISM's documentation](http://prism.oregonstate.edu/documents/PRISM_downloads_FTP.pdf) highlights `tdmean (mean dewpoint temperature)`, `vpdmin`, `vpdmax (min/max vapor pressure deficit)`  as "currently available ONLY as normals grids" instead of as a data grid. 

Successful pulling of this data should be validated.

**Comment by macmccann** [comment]
Closed with 479a6739daac361b5339bec163a161fdd756b5ea
